services:
  reverse-proxy:
    image: traefik:v3.2
    restart: unless-stopped
    networks:
      - shared-network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - "--ping=true"
      - "--ping.entrypoint=http"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.encodequerysemicolons=true"
      - "--entryPoints.http.http2.maxConcurrentStreams=50"
      - "--entrypoints.https.http.encodequerysemicolons=true"
      - "--entryPoints.https.http2.maxConcurrentStreams=50"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@tum.de"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--providers.docker=true"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.middlewares.errorpage.errors.status=501,502,503,504
      - traefik.http.middlewares.errorpage.errors.service=maintenance
      - traefik.http.middlewares.errorpage.errors.query=/index.html
    healthcheck:
      test: 'wget -qO- http://localhost:80/ping || exit 1'
      interval: 4s
      timeout: 2s
      retries: 5

  maintenance:
    image: nginx:alpine
    restart: unless-stopped
    configs:
      - source: maintenance-page
        target: /usr/share/nginx/html/index.html
      - source: nginx-default-config
        target: /etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-maintenance.entryPoints=http"
      - "traefik.http.routers.http-maintenance.middlewares=redirect-to-https"
      - "traefik.http.routers.http-maintenance.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.https-maintenance.entryPoints=https"
      - "traefik.http.routers.https-maintenance.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.https-maintenance.tls.certresolver=letsencrypt"
      - "traefik.http.routers.https-maintenance.tls=true"
      - "traefik.http.routers.http-maintenance.priority=1"
      - "traefik.http.routers.https-maintenance.priority=1"
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s

networks:
  shared-network:
    name: shared-network
    driver: bridge

configs:
  nginx-default-config:
    content: |
      server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;

        location / {
            rewrite ^ /index.html break;
        }
      }

  maintenance-page:
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <title>Proposal Review Maintenance</title>
      <meta http-equiv="refresh" content="5"/>
      <style>
          html, body { padding: 0; margin: 0; width: 100%; height: 100%; }
          * {box-sizing: border-box;}
          body { text-align: center; padding: 0; background: #353d47; color: #fff; font-family: sans-serif; }
          h1 { font-size: 50px; font-weight: 100; text-align: center;}
          body { font-weight: 100; font-size: 20px; color: #fff; text-align: center; display: -webkit-box; display: -ms-flexbox; display: flex; -webkit-box-pack: center; -ms-flex-pack: center; justify-content: center; -webkit-box-align: center; -ms-flex-align: center; align-items: center;}
          article { display: block; width: 700px; padding: 50px; margin: 0 auto; }
          a { color: #fff; font-weight: bold;}
          a:hover { text-decoration: none; }
      </style>
      <article>
          <svg class="warning" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 202.24 202.24"><defs><style>.cls-1{fill:#fff;}</style></defs><title>Asset 3</title><g id="Layer_2" data-name="Layer 2"><g id="Capa_1" data-name="Capa 1"><path class="cls-1" d="M101.12,0A101.12,101.12,0,1,0,202.24,101.12,101.12,101.12,0,0,0,101.12,0ZM159,148.76H43.28a11.57,11.57,0,0,1-10-17.34L91.09,31.16a11.57,11.57,0,0,1,20.06,0L169,131.43a11.57,11.57,0,0,1-10,17.34Z"/><path class="cls-1" d="M101.12,36.93h0L43.27,137.21H159L101.13,36.94Zm0,88.7a7.71,7.71,0,1,1,7.71-7.71A7.71,7.71,0,0,1,101.12,125.63Zm7.71-50.13a7.56,7.56,0,0,1-.11,1.3l-3.8,22.49a3.86,3.86,0,0,1-7.61,0l-3.8-22.49a8,8,0,0,1-.11-1.3,7.71,7.71,0,1,1,15.43,0Z"/></g></g></svg>
          <h1>We&rsquo;ll be back soon!</h1>
          <div>
              <p>We&rsquo;re performing some maintenance at the moment. Sorry for the inconvenience.</p>
              <p>&mdash; Your Proposal Review Administrators</p>
          </div>
      </article>
      </html>